#use_frameworks!
install! 'cocoapods', :deterministic_uuids => false
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

def aliyun_sdk
    pod 'AliyunVideoSDKPro/all', '3.36.0'
end

def aliyun_uicom

    pod "AUIUgsv/All", :path => "../"
    pod "AUIUgsv/AliyunVideoSDKPro_all", :path => "../"
    
    pod "AUIFoundation/All", "1.7.0"
    pod "AUIQueenCom/Queen", "1.7.0"

end

def common_demo_pods
    pod 'Masonry'
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'ZipArchive'
end


target 'AUIUgsvDemo' do
  
    common_demo_pods
    aliyun_uicom
    aliyun_sdk

end
