#use_frameworks!
install! 'cocoapods', :deterministic_uuids => false
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'


# ===================================集成音视频终端SDK===================================
def aliyun_demo_dependency_sdk
  pod 'AliVCSDK_Premium', '1.4.0'
end

# ===================================集成AUIFoundation===================================
def aliyun_demo_dependency_foundation
  pod 'AUIFoundation/All', :path => '../AUIFoundation/'
end

# ===================================Queen美颜集成===================================
def aliyun_demo_dependency_queen
  pod 'AUIQueenCom/AliVCSDK_Premium',  :path => '../AUIQueenCom/'
end

# ===================================直播推流集成===================================
def aliyun_demo_aui_live
  pod 'AlivcLiveDemo/AliVCSDK_Premium', :path => '../AlivcLiveDemo/'
  pod 'AlivcLiveDemo/List', :path => '../AlivcLiveDemo/'
  pod 'AlivcLiveDemo/LiveCameraPush', :path => '../AlivcLiveDemo/'
  pod 'AlivcLiveDemo/LivePlay', :path => '../AlivcLiveDemo/'
  pod 'AlivcLiveDemo/LiveLinkMic', :path => '../AlivcLiveDemo/'
  pod 'AlivcLiveDemo/LivePK', :path => '../AlivcLiveDemo/'
end

# ===================================播放器集成===================================
def aliyun_demo_aui_player
  pod 'AlivcPlayerDemo/AliVCSDK_Premium', :path => '../AlivcPlayerDemo/'
  pod 'AlivcPlayerDemo/All', :path => '../AlivcPlayerDemo/'
end

# ===================================短视频剪辑集成===================================
def aliyun_demo_aui_ugsv
  pod 'AlivcUgsv/AliVCSDK_Premium', :path => '../AlivcUgsvDemo/'
  pod 'AlivcUgsv/All', :path => '../AlivcUgsvDemo/'
end


target 'AlivcAIODemo' do
  pod 'WPKMobi', '~> 1.3.6' #itrace崩溃接入
  
  aliyun_demo_dependency_sdk
  aliyun_demo_dependency_queen
  aliyun_demo_dependency_foundation

  aliyun_demo_aui_ugsv
  aliyun_demo_aui_player
  aliyun_demo_aui_live
  
end


post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
    end
end
