#use_frameworks!
install! 'cocoapods', :deterministic_uuids => false
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'


# ===================================集成音视频终端SDK===================================
def aliyun_demo_dependency_sdk
  pod 'AliVCSDK_Premium', '1.6.0'
end

# ===================================集成AUIFoundation===================================
def aliyun_demo_dependency_foundation
  pod 'AUIFoundation/All', :path => '../AUIFoundation/'
end

# ===================================Queen美颜集成===================================
def aliyun_demo_dependency_queen
  pod 'AUIQueenCom/AliVCSDK_Premium',  :path => '../AUIQueenCom/'
end

# ===================================直播推流集成===================================
def aliyun_demo_aui_live
  pod 'AUILive/AliVCSDK_Premium', :path => '../AUILive/'
  pod 'AUILive/List', :path => '../AUILive/'
  pod 'AUILive/LiveCameraPush', :path => '../AUILive/'
  pod 'AUILive/LivePlay', :path => '../AUILive/'
  pod 'AUILive/LiveLinkMic', :path => '../AUILive/'
  pod 'AUILive/LivePK', :path => '../AUILive/'
  pod 'AUILive/LiveRtsPlay', :path => '../AUILive/'
end

# ===================================播放器集成===================================
def aliyun_demo_aui_player
  pod 'AUIPlayer/AliVCSDK_Premium', :path => '../AUIPlayer/'
  pod 'AUIPlayer/All', :path => '../AUIPlayer/'
end

# ===================================短视频剪辑集成===================================
def aliyun_demo_aui_ugsv
  pod 'AUIUgsv/AliVCSDK_Premium', :path => '../AUIUgsv/'
  pod 'AUIUgsv/All', :path => '../AUIUgsv/'
end


target 'AlivcAIODemo' do
  pod 'WPKMobi', '~> 1.3.6' #itrace崩溃接入
  
  aliyun_demo_dependency_sdk
  aliyun_demo_dependency_queen
  aliyun_demo_dependency_foundation

  aliyun_demo_aui_ugsv
  aliyun_demo_aui_player
  aliyun_demo_aui_live
  
end


post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
    end
end
